name: Java Maven Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        auth-type: service-principal

    - name: Docker login to ACR
      run: az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build Docker Image
      run: docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/my-java-app:latest .

    - name: Push Docker Image
      run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/my-java-app:latest
